// CATEGORIES
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const RECEIVE_CATEGORIES_AND_PAGES = 'RECEIVE_CATEGORIES_AND_PAGES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_PUSH_CATEGORY = 'RECEIVE_PUSH_CATEGORY';
export const ADD_PAGE_CATEGORY = 'ADD_PAGE_CATEGORY';
export const DELETE_PAGE_CATEGORY = 'DELETE_PAGE_CATEGORY';

// EDIT CATEGORIES
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY_TITLE = 'UPDATE_CATEGORY_TITLE';
export const TOGGLE_EDIT_CATEGORY = 'TOGGLE_EDIT_CATEGORY';
export const TOGGLE_COLOR_PICKER = 'TOGGLE_COLOR_PICKER';
export const REMOVE_CAT_FROM_PAGE = 'REMOVE_CAT_FROM_PAGE';
export const SET_EDIT_CAT_COLOR = 'SET_EDIT_CAT_COLOR';
export const CONFIRM_DELETE = 'CONFIRM_DELETE';

// SEARCHING CATEGORIES
export const ADD_SEARCH_CATEGORY = 'ADD_SEARCH_CATEGORY';
export const REMOVE_SEARCH_CATEGORY = 'REMOVE_SEARCH_CATEGORY';
export const CLEAR_SEARCH_CATEGORIES = 'CLEAR_SEARCH_CATEGORIES';

// BLACKLIST
export const ADD_TO_BLACKLIST = 'ADD_TO_BLACKLIST';
export const REMOVE_FROM_BLACKLIST = 'REMOVE_FROM_BLACKLIST';
export const RECEIVE_BLACKLIST = 'RECEIVE_BLACKLIST';

// PAGES
export const RECEIVE_PAGE_INFO = 'RECEIVE_PAGE_INFO';
export const TOGGLE_SHOW_STARRED = 'TOGGLE_SHOW_STARRED';
export const UPDATE_PAGE_CATS = 'UPDATE_PAGE_CATS';

// STARS
export const TOGGLE_STAR = 'TOGGLE_STAR';
export const UPDATE_CURRENT_STAR = 'UPDATE_CURRENT_STAR';

// TABS
export const RECEIVE_TABS = 'RECEIVE_TABS';

// TIMES
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
export const UPDATE_TIMEFRAME = 'UPDATE_TIMEFRAME';

// LOOKBACK
export const SWITCH_LOOKBACK_SELECTION = 'SWITCH_LOOKBACK_SELECTION';

//SEARCH
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SET_CURR_DOM = 'SET_CURR_DOM';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

// USER
export const RECEIVE_USER_TOKEN = 'RECEIVE_USER_TOKEN';
export const USER_ERROR = 'USER_ERROR';
export const NO_USER_ERROR = 'NO_USER_ERROR';
export const MISMATCH_PASSWORD = 'MISMATCH_PASSWORD';
export const EMPTY_FIELD = 'EMPTY_FIELD';
export const RECEIVE_USER_TOKEN_FROM_CHROME = 'RECEIVE_USER_TOKEN_FROM_CHROME';

// POPUP
export const CHANGE_POPUP_TAB = 'CHANGE_POPUP_TAB';
export const USER_LOGOUT = 'USER_LOGOUT';
export const FORGOT_MY_PASSWORD_PAGE = 'FORGOT_MY_PASSWORD_PAGE';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const POPUP_STATUS = 'POPUP_STATUS';
export const SET_DURATION_ID = 'SET_DURATION_ID';
export const RECEIVE_ADDED_SESSION = 'RECEIVE_ADDED_SESSION';

// MISC
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const UPDATE_DISPLAY_DOMAIN = 'UPDATE_DISPLAY_DOMAIN';
export const RECEIVE_DOMAIN_INFO = 'RECEIVE_DOMAIN_INFO';
export const TOGGLE_DOMAIN_CLICKED = 'TOGGLE_DOMAIN_CLICKED';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
