// CATEGORIES
export const ADD_CATEGORY = 'addCategory';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const REQUEST_PUSH_CATEGORY = 'REQUEST_PUSH_CATEGORY';
export const RECEIVE_PUSH_CATEGORY = 'RECEIVE_PUSH_CATEGORY';

// PAGES
export const ADD_PAGE = 'addPage';
export const RECEIVE_PAGES = 'RECEIVE_PAGES';
export const REQUEST_PAGES = 'REQUEST_PAGES';
export const RECEIVE_PAGE_INFO = 'RECEIVE_PAGE_INFO';

//STARS
export const TOGGLE_STAR = 'TOGGLE_STAR';
export const REQUEST_STAR = 'REQUEST_STAR';
export const RECEIVE_STAR = 'RECEIVE_STAR';
export const UPDATE_CURRENT_STAR = 'UPDATE_CURRENT_STAR'; 
