export const ADD_PAGE = 'addPage';
export const ADD_CATEGORY = 'addCategory';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const REQUEST_PUSH_CATEGORY = 'REQUEST_PUSH_CATEGORY';
export const RECEIVE_PUSH_CATEGORY = 'RECEIVE_PUSH_CATEGORY';
